module.exports = {
  mapWidth: 40,
  mapHeight: 20,
  worldWidth: 129,
  worldHeight: 129,
  colors: {
    black: 'black',
    black2: 'blackBright',
    grey: 'blackBright',
    grey2: 'blackBright',
    gray: 'blackBright',
    gray2: 'blackBright',
    red: 'red',
    red2: 'redBright',
    pink: 'redBright',
    green: 'green',
    green2: 'greenBright',
    yellow: 'yellow',
    yellow2: 'yellowBright',
    blue: 'blue',
    blue2: 'blue',
    magenta: 'magenta',
    magenta2: 'magentaBright',
    teal: 'cyan',
    teal2: 'cyanBright',
    cyan: 'cyan',
    cyan2: 'cyanBright',
    white: 'white',
    white2: 'whiteBright',
    none: null
  }
}
